server.port: 8083

spring:
  application:
    name: message-service
  zipkin:
    locator:
      discovery:
        enabled: true

security.basic.enabled: false
management.security.enabled: false

spring.cloud.stream.bindings.output.destination: sleuth-test
logging.level.org.springframework.web.servlet.DispatcherServlet: DEBUG
