---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: "8"

inputs:
- name: sleuth

outputs:
- name: package-output

params:
  MAVEN_OPTS: ""
  MAVEN_CONFIG_FILE: ""

run:
  path: sleuth/ci/tasks/package.sh
