---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: "8"

inputs:
- name: sleuth

outputs:
- name: smoke-tests-output

params:
  MAVEN_OPTS: ""
  MAVEN_CONFIG: ""

run:
  path: sleuth/ci/tasks/smoke-tests.sh
