---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: "8"

inputs:
- name: sleuth
- name: apps-urls

outputs:
- name: smoke-tests-output

params:
  MAVEN_OPTS: ""
  MAVEN_CONFIG_FILE: ""

run:
  path: sleuth/ci/tasks/smoketests.sh
