---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotalservices/docker-concourse-cf-tools
    tag: "latest"

inputs:
- name: sleuth
- name: package-output

run:
  path: sleuth/ci/tasks/stop-apps.sh
