server.port: 9411
# this is the default: zipkin.storage.type: mem

security.basic.enabled: false
management.security.enabled: false

logging.level.org.springframework.web.servlet.DispatcherServlet: DEBUG
