server:
  port: 8082

spring:
  application:
    name: message-client
  zipkin:
    locator:
      discovery:
        enabled: true

security:
  basic:
    enabled: false

management:
  security:
    enabled: false


logging.level.org.springframework.web.servlet.DispatcherServlet: DEBUG
