---
resources:
- name: sleuth
  type: git
  source:
    uri: https://github.com/ukabu/sleuth.git
    branch: master

- name: deploy-cf
  type: cf
  source:
    api: {{pcf-api}}
    username: {{pcf-user}}
    password: {{pcf-password}}
    organization: {{pcf-org}}
    space: {{pcf-space}}

jobs:
- name: test
  plan:
  - get: sleuth
    trigger: true
  - task: test
    file: sleuth/ci/tasks/test.yml
    params:
      MAVEN_OPTS: {{maven-opts}}
      MAVEN_CONFIG: {{maven-config}}

- name: deploy
  plan:
  - get: sleuth
    trigger: true
    passed: [test]
  - task: package
    file: sleuth/ci/tasks/package.yml
    params:
      MAVEN_OPTS: {{maven-opts}}
      MAVEN_CONFIG: {{maven-config}}
  - put: deploy-cf
    params:
      manifest: package-output/manifest.yml

- name: stop-apps
  plan:
  - get: sleuth
    passed: [deploy]
    trigger: true
  - task: stop-apps
    file: sleuth/ci/tasks/stop-apps.yml
    params:
      PCF_API: {{pcf-api}}
      PCF_ORG: {{pcf-org}}
      PCF_SPACE: {{pcf-space}}
      PCF_USER: {{pcf-user}}
      PCF_PASWORD: {{pcf-password}}
