---
resources:
- name: sleuth
  type: git
  source:
    uri: https://github.com/ukabu/sleuth.git
    branch: master

# - name: deploy-cf
#   type: cf
#   source:
#     api: {{cf-api}}
#     username: {{cf-user}}
#     password: {{cf-password}}
#     organization: {{cf-org}}
#     space: {{cf-space}}

jobs:
- name: test
  plan:
  - get: sleuth
    trigger: true
  - task: test
    file: sleuth/ci/tasks/test.yml
    params:
      MAVEN_OPTS: {{maven-opts}}
      MAVEN_CONFIG: {{maven-config}}

- name: deploy
  plan:
  - get: sleuth
    trigger: true
    passed: [test]
  - task: package
    file: sleuth/ci/tasks/package.yml
    params:
      MAVEN_OPTS: {{maven-opts}}
      MAVEN_CONFIG: {{maven-config}}
  # - put: deploy-cf
  #   params:
  #     manifest: package-output/manifest.yml
